<?php

namespace AppBundle\Repository;

/**
 * EcouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcouteRepository extends \Doctrine\ORM\EntityRepository
{
}
