app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_comment_api:
    type: rest
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin




